#!/usr/bin/env python3
"""Generate cpp/src/unicode_printable.inc: code point ranges for which
str.isprintable() is False in the running CPython (used by repr())."""
import sys, unicodedata
ranges = []
start = None
for cp in range(0x110000):
    np = not chr(cp).isprintable()
    if np and start is None:
        start = cp
    elif not np and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))
out = sys.stdout
out.write("// Generated by tools/gen_printable.py from Python %s (Unicode %s).\n"
          % (sys.version.split()[0], unicodedata.unidata_version))
out.write("// Inclusive ranges of code points that are NOT printable.\n")
for a, b in ranges:
    out.write("{0x%X, 0x%X},\n" % (a, b))
